version: '3.8'

services:
  frontend:
    image: frontendimage:$BUILD_TAG
    ports:
      - "8080:80"
    restart: always
    networks:
      - frontend-network
    

networks:
  frontend-network:
    driver: bridge
 
