version: '3.8'

services:
  frontend:
    image: mmfrontendimage
    ports:
      - "8089:80"
    restart: always
    networks:
      - frontend-network
    

networks:
  frontend-network:
    driver: bridge
 
